blog/articles/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article = Blueprint(
    "article",
    __name__,
    static_folder="../static",
    url_prefix="/articles/",
)


@article.route("/", methods=["GET"])
def article_list():
    articles = Article.query.all()
    # call RPC method
    # count_articles: Dict = requests.get(
    #     f"{API_URL}/api/articles/event_get_count/").json()
    return render_template(
        "articles/list.html",
        articles=articles,
        # count_articles=count_articles["count"],
    )


@article.route("/<int:pk>")
@login_required
def article_details(pk: int):
    _article = Article.query.filter_by(id=pk).options(joinedload(Article.tags)).one_or_none()
    if _article is None:
        raise NotFound
    return render_template(
        "articles/details.html",
        article=_article,
    )


@article.route("/create", methods=["GET"])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    return render_template("articles/create.html", form=form)


@article.route("/", methods=["POST"])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), body=form.body.data)

        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for("article.article_details", pk=_article.id))

    return render_template("articles/create.html", form=form)

blog/users/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models import User

user = Blueprint(
    "user",
    __name__,
    static_folder="../static",
    url_prefix="/users/",
)


@user.route("register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("user.profile", pk=current_user.id))

    form = UserRegisterForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        _user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)
        return redirect(url_for("index.index_page"))

    return render_template("users/register.html", form=form)


@user.route("/")
@login_required
def user_list():
    users = User.query.all()
    return render_template(
        "users/list.html",
        users=users,
    )


@user.route("/<int:pk>")
@login_required
def profile(pk: int):
    user = User.query.filter_by(id=pk).one_or_none()
    # call RPC method
    # count_articles: Dict = requests.get(
    #     f"{API_URL}/api/authors/{pk}/event_get_articles_count/").json()
    if user is None:
        raise NotFound(f"User #{pk} doesn't exist!")
    return render_template(
        "users/profile.html",
        user=user,
        # count_articles=count_articles["count"],
    )

blog/views.py
from flask import Blueprint, render_template

index = Blueprint("index", __name__, static_folder="./static")


@index.route("/")
def index_page():
    return render_template("index.html")

blog/templates/includes/footer.html
<div class="container-fluid fixed-bottom" id="footer">
  <hr>
  <p class="text-center"><small>2022 &copy; All rights reserved</small></p>
</div>

blog/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffdb58;" id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" 
      href="{{ url_for('index.index_page') }}">Oh, my BLOG!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% for (endpoint, label) in [
                                    ("index.index_page", "Home"), 
                                    ("user.user_list", "Users"), 
                                    ("author.author_list", "Authors"), 
                                    ("article.article_list", "Articles"),
                                    ("tag.tag_list", "Tags"),
                                    ("api-docs.openapi_swagger_ui", "Docs"),
                                    ] %}
          <a class="nav-link {% if request.endpoint == endpoint %}active{% endif %}" aria-current="page" 
            href="{{ url_for(endpoint) }}">{{ label }}</a>
        {% endfor %}
        {% if current_user.is_staff %}
          <a class="nav-link" aria-current="page" 
            href="{{ url_for("admin.index") }}">ADMINPANEL</a>
        {% endif %}
        {% if current_user.is_anonymous %}
          <a class="nav-link" aria-current="page" 
            href="{{ url_for('user.register') }}">Registration</a>
        {% endif %}
        {% if current_user.is_authenticated %}
          <a class="nav-link" aria-current="page" 
            href="{{ url_for('article.create_article_form') }}">
            Create article</a>
          <a class="nav-link" aria-current="page" 
            href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
          <a class="nav-link" aria-current="page" 
            href="{{ url_for('auth.login') }}">Login</a>
        {% endif %}
      </div>
    </div>
    {% if current_user.is_authenticated %}
      <span class="navbar-text">
        Hi, {{ current_user.username|capitalize }}
      </span>
    {% endif %}
  </div>
</nav>