blog/users/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models import User

user = Blueprint(
    "user",
    __name__,
    static_folder="../static",
    url_prefix="/users/",
)


@user.route("register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("user.profile", pk=current_user.id))

    form = UserRegisterForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        _user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)
        return redirect(url_for("index.index_page"))

    return render_template("users/register.html", form=form)


@user.route("/")
@login_required
def user_list():
    users = User.query.all()
    return render_template(
        "users/list.html",
        users=users,
    )


@user.route("/<int:pk>")
@login_required
def profile(pk: int):
    user = User.query.filter_by(id=pk).one_or_none()
    # call RPC method
    # count_articles: Dict = requests.get(
    #     f"{API_URL}/api/authors/{pk}/event_get_articles_count/").json()
    if user is None:
        raise NotFound(f"User #{pk} doesn't exist!")
    return render_template(
        "users/profile.html",
        user=user,
        # count_articles=count_articles["count"],
    )

blog/views.py
from flask import Blueprint, render_template

index = Blueprint("index", __name__, static_folder="./static")


@index.route("/")
def index_page():
    return render_template("index.html")

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
</head>
<body>

    {% include "includes/navbar.html" %}

    <div class="container" id="content">
        {% block content %}{% endblock content %}
    </div>

    {% include "includes/footer.html" %}

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcom to Oh, my Blog!{% endblock title %}

{% block content %}
<h1 class="display-4">Oh, my Blog! welcomes you, O great
  {% if current_user.is_authenticated %}
    {{ current_user.username|capitalize }}
  {% else %}
    Anonymous
  {% endif %}!</h1>
{% endblock content %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffdb58;">
  <div class="container-fluid">
    <a class="navbar-brand" 
      href="{{ url_for("index.index_page") }}">Oh, my BLOG!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" 
          href="{{ url_for("index.index_page") }}">Home</a>
        <a class="nav-link" 
          href="{{ url_for("user.user_list") }}">Users</a>
        <a class="nav-link" 
          href="#">Articles</a>
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </div>
    </div>
  </div>
</nav>