blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import (SelectMultipleField, StringField, SubmitField,
                     TextAreaField)
from wtforms.validators import DataRequired


class CreateArticleForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    body = TextAreaField("Body", validators=[DataRequired()])
    tags = SelectMultipleField("Tags", coerce=int)
    submit = SubmitField("Publish")

blog/articles/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article = Blueprint(
    "article",
    __name__,
    static_folder="../static",
    url_prefix="/articles/",
)


@article.route("/", methods=["GET"])
def article_list():
    articles = Article.query.all()
    # call RPC method
    # count_articles: Dict = requests.get(
    #     f"{API_URL}/api/articles/event_get_count/").json()
    return render_template(
        "articles/list.html",
        articles=articles,
        # count_articles=count_articles["count"],
    )


@article.route("/<int:pk>")
@login_required
def article_details(pk: int):
    _article = Article.query.filter_by(id=pk).options(joinedload(Article.tags)).one_or_none()
    if _article is None:
        raise NotFound
    return render_template(
        "articles/details.html",
        article=_article,
    )


@article.route("/create", methods=["GET"])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    return render_template("articles/create.html", form=form)


@article.route("/", methods=["POST"])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), body=form.body.data)

        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for("article.article_details", pk=_article.id))

    return render_template("articles/create.html", form=form)

blog/tags/views.py
from flask import Blueprint, render_template
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.models import Tag

tag = Blueprint(
    "tag",
    __name__,
    static_folder="../static",
    url_prefix="/tags/",
)


@tag.route("/", methods=["GET"])
def tag_list():
    tags = Tag.query.all()
    return render_template(
        "tags/list.html",
        tags=tags,
    )


@tag.route("/<int:pk>")
def tag_details(pk: int):
    _tag = Tag.query.filter_by(id=pk).options(joinedload(Tag.articles)).one_or_none()
    if _tag is None:
        raise NotFound
    return render_template(
        "tags/details.html",
        tag=_tag,
    )

blog/templates/articles/create.html
{% extends "base.html" %}
{% from "macro/formhelpers.html" import render_field %}

{% block title %}Create article{% endblock title %}

{% block content %}

<h1 class="display-4">Create article</h1>

<form method="POST" action={{ url_for("article.create_article") }}>
  {{ form.csrf_token }}

  {% for field in ["title", "body", "tags"] %}
    {{ render_field(form[field]) }}
  {% endfor %}
  
  {{ form.submit(class="btn", style="background-color: #ffdb58;") }}
</form>

{% endblock content %}

blog/templates/articles/details.html
{% extends "base.html" %}

{% block title %}
  Article #{{ article.id }}: {{ article.title }}
{% endblock title %}

{% block content %}
<div>
  <h1 class="display-4">{{ article.title|capitalize }}</h1>
  <div>
    <p>{{ article.body }}</p>
  </div>
  <div class="row">
    <div class="col-6">
      <div>Published {{ article.created_at.strftime("%d.%m.%Y %H:%M") }}</div>
      <div>Author 
        <a href="{{ url_for('user.profile', pk=article.author.user_id) }}">
          {{ article.author.user.username }} ({{ article.author.id }})</a>
      </div>
    </div>
    <div class="col-6">
      {% for tag in article.tags %}
        <a href="{{ url_for('tag.tag_details', pk=tag.id) }}" 
          class="btn badge bg-primary">{{ tag.name }}</a>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/articles/list.html
{% extends "base.html" %}

{% block title %}Article List{% endblock title %}

{% block content %}

<h1 class="display-4">Articles (count: {{ count_articles }}, received from an RPC call):</h1>

<div class="row justify-content-md-start">
  {% for article in articles %}
    <div class="card col-6" style="width: 18rem;" id="{{ article.id }}">
      <div class="card-body">
        <h5 class="card-title">Article #{{ article.id }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <a href="{{ url_for('article.article_details', pk=article.id) }}">
            {{ article.title|capitalize }}</a></h6>
        <p class="card-text">{{ article.body }}</p>
        <div>Published {{ article.created_at.strftime("%d.%m.%Y %H:%M") }}</div>
        <div>Author 
          <a href="{{ url_for('user.profile', pk=article.author.user.id) }}" class="card-link">{{ article.author.user.username }}</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock content %}